basePath: /
host: localhost:7001
info:
  contact: {}
  description: This is the API service for Gin Template.
  title: Gin Template Api
  version: "1.0"
paths: {}
securityDefinitions:
  AdminAuthToken:
    description: (For Admin Panel) Type "Bearer" followed by a space and the token
      obtained from the admin login endpoint.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
